// Generated by CoffeeScript 1.9.2
(function() {
  var User, data;

  data = require('../testData.json');

  User = require('../models/user.js');

  module.exports = {
    test: function(req, res) {}
  };

}).call(this);
